### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by maracuja-juice** [ultimate-ttt/ultimate-ttt#127]
Make it searchable on Google!

**Comment by Leo1212** [comment]
Hi @maracuja-juice I think I could help you, if you want to ;)

**Comment by maracuja-juice** [comment]
@Leo1212 Hey. Yes, would be great.

**Comment by maracuja-juice** [comment]
@Leo1212 
Feel free to make a PR that adds an appropriate description:

![image](https://user-images.githubusercontent.com/16801528/56433942-f2f04e80-62d2-11e9-9895-9d356ba3d27c.jpeg)
